[versions]
checkerframework = "3.52.0"
jmh = "1.37"

[libraries]
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
checker = { group = "org.checkerframework", name = "checker", version.ref = "checkerframework" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "6.0.1" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "6.0.1" }

[bundles]

[plugins]
checkerframework = { id = "org.checkerframework", version = "0.6.61" }
publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }